update=Monday, 23 December 2013 07:49:45 am
version=1
last_client=kicad
[general]
version=1
[eeschema]
version=1
PageLayoutDescrFile=
SubpartIdSeparator=0
SubpartFirstId=65
LibDir=
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=parts/lib_w_microcontrollers/w_microcontrollers
LibName2=parts/kicad/power
LibName3=parts/lib_w_device/w_device
LibName4=parts/kicad/atmel
LibName5=parts/rancidbacon/battery-cr2032
LibName6=parts/lib_w_connectors/w_connectors
LibName7=parts/lib_w_device/sw_push_alternate_pinout_via_w_device_lib
[cvpcb]
version=1
NetIExt=net
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=
UseCmpFile=1
PadDrill=0.6
PadDrillOvalY=0.6
PadSizeH=1.5
PadSizeV=1.5
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.09999999999999999
ModuleOutlineThickness=0.15
[pcbnew/libraries]
LibDir=
LibName1=parts/rancidbacon/battery-cr2032-retainer-keystone-3003
LibName2=parts/rancidbacon/OMRON-PUSH-BUTTON-B3SN-3112P
LibName3=parts/smisioto/mod_pin_strip/w_pin_strip
LibName4=parts/smisioto/mod_smd_cap/w_smd_cap
LibName5=parts/smisioto/mod_smd_leds/w_smd_leds
LibName6=parts/smisioto/mod_smd_lqfp/w_smd_lqfp
LibName7=parts/smisioto/mod_smd_resistors/w_smd_resistors
